UserParameter=container.discover,/opt/claranet/zabbix/bin/container_disco.sh
UserParameter=container.discover.shortid,/opt/claranet/zabbix/bin/container_disco_short.sh
UserParameter=docker.stat[*],grep $1 /tmp/zab.val | awk '{print $NF}'
UserParameter=docker.totals[*],docker $1 ls | awk NR!=1 | wc -l
UserParameter=container.active[*],docker inspect -f '{{.State.Running}}' $1 | sed -e 's/true/1/g' | sed -e 's/false/0/g'
UserParameter=containers.running,/rootfs/usr/bin/docker ps -q | wc -l
UserParameter=containers.total,/rootfs/usr/bin/docker ps -a -q | wc -l
UserParameter=container.procs[*],/rootfs/usr/bin/docker exec -t $1 ps -aux --no-headers | wc -l
UserParameter=container.stats[*],/rootfs/usr/bin/docker stats --no-stream --format "table {{.Container}}\t{{.$2}}" $1 | awk '{if (NR!=1) {print}}' | awk '{print $NF}'
UserParameter=container.net.in[*],humanfriendly --parse-size=`docker stats --no-stream --format "table {{.Container}}\t{{.NetIO}}" | grep $1 | awk '{print $(NF-2)}'`
UserParameter=container.net.out[*],humanfriendly --parse-size=`docker stats --no-stream --format "table {{.Container}}\t{{.NetIO}}" | grep $1 | awk '{print $NF}'`
UserParameter=container.block.in[*],humanfriendly --parse-size=`docker stats --no-stream --format "table {{.Container}}\t{{.BlockIO}}" | grep $1 | awk '{print $(NF-2)}'`
UserParameter=container.block.out[*],humanfriendly --parse-size=`docker stats --no-stream --format "table {{.Container}}\t{{.BlockIO}}" | grep $1 | awk '{print $NF}'`
UserParameter=container.pids[*],/rootfs/usr/bin/docker stats --no-stream --format "table {{.Container}}\t{{.PIDs}}" $1 | awk '{if (NR!=1) {print}}' | awk '{print $NF}'
UserParameter=container.cpu[*],grep -i $2 /rootfs/sys/fs/cgroup/cpuacct/docker/$1/cpuacct.stat | sed 's/[^0-9]*//g'
UserParameter=container.cpu.perc[*],/rootfs/usr/bin/docker stats --no-stream --format "table {{.Container}}\t{{.CPUPerc}}" $1 | awk '{if (NR!=1) {print}}' | awk '{print $NF}' | sed 's/[^.0-9][^.0-9]*/ /g'
UserParameter=container.cpu.ns[*],cat /rootfs/sys/fs/cgroup/cpu,cpuacct/docker/$1/cpuacct.usage
UserParameter=container.cpu.thr[*], grep $2 /rootfs/sys/fs/cgroup/cpuacct/docker/$1/cpu.stat | awk '{print $NF}'
UserParameter=container.mem[*],cat /rootfs/sys/fs/cgroup/memory/docker/$1/$2
UserParameter=container.uptime[*],/rootfs/usr/bin/docker ps --no-trunc --format '{{.ID}} {{.Status}}' | grep $1 | awk '{print $(NF-2)" "$(NF-1)" "$NF}'
